GUILD_ID = 1117768495531294770

CARGO_COORDENADOR = "Coordenador"
CARGO_ALUNO = "Aluno"
CARGO_PROFESSOR = "Professor"
CARGO_DEV = "Dev"
CARGO_EGRESSO = "Egresso"
CARGO_PRETENDENTE = "Pretendente"
